# This is a basic workflow to help you get started with Actions

name: Blog deploy

# Controls when the workflow  will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 🔑 Setup SSH
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATEKEY }}

      - name: git init
        run: |
            git config --global user.email "lcj@yusur.tcch"
            git config --global user.name "lcj"
            git status
            git submodule update --init --recursive
            ssh-add - <<< "${{ secrets.PAGE_PRIVATEKEY }}"

      # Runs a set of commands using the runners shell
      - name: Set Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.13'

      - name: 缓存 Hexo
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: Npm Install
        #if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm update
          npm install hexo-cli -g
          npm install --save
          npm i hexo -g

      - name: Hexo Deploy
        run: |
          hexo clean
          hexo generate
          hexo deploy
